In [1]:
import numpy as np
students = np.array([
    [67, 94, 65],
    [78, 92, 68],
    [59, 92, 87]
    ])
students

array([[67, 94, 65],
       [78, 92, 68],
       [59, 92, 87]])

In [3]:
import pandas as pd

pd.DataFrame(data=students,
            index=['stu1','stu2','stu3'],
            columns=['國文','英文','數學']
            )

      國文  英文  數學
stu1  67  94  65
stu2  78  92  68
stu3  59  92  87

In [20]:
data = np.random.randint(50, high=100, size=(50,5))
students = pd.DataFrame(data,
            columns=['國文', '英文', '數學', '地理', '探討'])
students

    國文  英文  數學  地理  探討
0   72  52  96  55  98
1   58  96  89  94  57
2   53  81  59  86  54
3   63  83  97  65  86
4   65  90  78  64  62
5   62  73  78  71  72
6   79  51  60  68  72
7   82  99  97  96  77
8   85  68  59  71  52
9   92  65  80  84  59
10  84  88  85  99  56
11  76  61  56  81  60
12  80  59  79  68  73
13  77  73  57  86  71
14  89  87  59  74  88
15  86  82  68  80  88
16  61  52  50  98  82
17  58  85  91  93  73
18  97  81  58  53  93
19  85  58  52  54  92
20  65  86  53  60  53
21  62  77  79  59  66
22  89  56  83  68  91
23  88  59  65  75  68
24  67  78  53  86  93
25  66  67  53  98  50
26  99  84  94  82  72
27  84  91  50  61  90
28  77  83  91  69  65
29  86  52  56  60  72
30  60  80  87  51  91
31  67  67  89  67  97
32  67  92  62  80  91
33  67  95  56  95  90
34  65  95  98  84  86
35  76  95  65  56  78
36  98  69  54  51  78
37  77  65  88  71  63
38  82  70  57  75  53
39  85  50  90  79  51
40  54  89  56  96  58
41  51  98  81  55  58
42  55  56  62  61  90
43  80  63  83  98  93
44  89  79  80  85  58
45  51  91  75  75  58
46  96  91  66  99  64
47  55  96  52  60  91
48  87  61  56  91  60
49  92  63  79  93  60